# Generated by Django 4.0.5 on 2022-06-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=30)),
                ('pais_contacto', models.CharField(max_length=20)),
                ('correo_contacto', models.CharField(max_length=50)),
                ('consulta', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
