# Generated by Django 4.0.5 on 2022-06-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_alter_contacto_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
    ]
