# Generated by Django 3.0.7 on 2022-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0002_auto_20220607_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
