# Generated by Django 4.0.5 on 2022-06-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0002_experiencias_image_experiencias_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='experiencias'),
        ),
    ]
