# Generated by Django 4.0.5 on 2022-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0003_auto_20220607_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
