# Generated by Django 4.0.5 on 2022-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0007_alter_experiencias_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='cuerpo',
            field=models.TextField(max_length=20000),
        ),
    ]
