# Generated by Django 4.0.5 on 2022-07-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0008_alter_experiencias_cuerpo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencias',
            options={'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencias'},
        ),
    ]
