# Generated by Django 4.0.4 on 2022-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tramites', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=5000)),
            ],
        ),
    ]
