# Generated by Django 4.0.5 on 2022-06-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_alter_tramites_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramites',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_tramites/'),
        ),
    ]
