# Generated by Django 4.0.5 on 2022-06-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_alter_tramites_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramites',
            options={'verbose_name': 'Tramites', 'verbose_name_plural': 'Tramites'},
        ),
    ]
