# Generated by Django 4.0.5 on 2022-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_alter_tramites_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramites',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
