# Generated by Django 4.0.5 on 2022-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0006_alter_tramites_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramites',
            name='descripcion',
            field=models.TextField(max_length=20000),
        ),
    ]
