# Generated by Django 4.0.5 on 2022-07-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0007_alter_tramites_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramites',
            options={'verbose_name': 'Tramite', 'verbose_name_plural': 'Tramites'},
        ),
    ]
