# Generated by Django 4.0.5 on 2022-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0008_alter_tramites_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramites',
            name='autor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
