# Generated by Django 4.0.5 on 2022-06-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_delete_perfilusuario_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(default='usuario.jpg', upload_to='blog_viaje-GomezMogniLavezzo'),
        ),
    ]
