# Generated by Django 4.0.5 on 2022-06-23 19:38

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_remove_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redes_sociales',
            field=models.URLField(null=multiprocessing.sharedctypes.Value),
            preserve_default=multiprocessing.sharedctypes.Value,
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(null=multiprocessing.sharedctypes.Value),
            preserve_default=multiprocessing.sharedctypes.Value,
        ),
    ]
