# Generated by Django 4.0.5 on 2022-06-23 20:43

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_user_redes_sociales_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='redes_sociales',
            field=models.CharField(max_length=100, null=multiprocessing.sharedctypes.Value),
        ),
    ]
