# Generated by Django 4.0.5 on 2022-06-21 19:20

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_alter_user_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=multiprocessing.sharedctypes.Value, upload_to='media/blog_viaje-GomezMogniLavezzo'),
        ),
    ]
