# Generated by Django 4.0.5 on 2022-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_imagenes_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_inicio',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_Imagenes_Inicio/'),
        ),
        migrations.AlterField(
            model_name='imagenes_inicio',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_Imagenes_Inicio/'),
        ),
        migrations.AlterField(
            model_name='imagenes_inicio',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_Imagenes_Inicio/'),
        ),
    ]
