# Generated by Django 4.0.5 on 2022-06-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_alter_imagenes_inicio_imagen1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes_inicio',
            old_name='imagen1',
            new_name='image',
        ),
    ]
