# Generated by Django 4.0.5 on 2022-06-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='usuario1.jpg', upload_to='blog_viaje-GomezMogniLavezzo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='cuenta.imagen'),
        ),
    ]
