# Generated by Django 4.0.5 on 2022-06-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_rename_imagen1_imagenes_inicio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes_inicio',
            old_name='image',
            new_name='imagen1',
        ),
    ]
