# Generated by Django 4.0.5 on 2022-06-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_rename_image_imagenes_inicio_imagen1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenes_Inicio',
        ),
    ]
