# Generated by Django 4.0.5 on 2022-06-21 20:25

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0011_alter_user_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=multiprocessing.sharedctypes.Value, upload_to=''),
        ),
    ]
