# Generated by Django 4.0.5 on 2022-06-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0012_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(upload_to='profile_image'),
        ),
        migrations.DeleteModel(
            name='imagen',
        ),
    ]
