# Generated by Django 4.0.5 on 2022-07-03 16:19

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0012_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='redes_sociales',
            field=models.URLField(max_length=100, null=multiprocessing.sharedctypes.Value),
        ),
    ]
