# Generated by Django 4.0.5 on 2022-07-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0013_alter_user_redes_sociales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
