# Generated by Django 4.0.5 on 2022-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0014_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='redes_sociales',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
