# Generated by Django 4.0.5 on 2022-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0015_alter_user_redes_sociales_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='redes_sociales',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
