# Generated by Django 4.0.5 on 2022-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0016_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='imagen',
            field=models.ImageField(default='WhatsApp_Image_2022-06-21_at_3.27.06_PM', upload_to='profile_image'),
        ),
    ]
