# Generated by Django 4.0.5 on 2022-06-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0017_alter_user_profile_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'perfil de usuario', 'verbose_name_plural': 'perfiles de usuario'},
        ),
    ]
